services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "5432:5432" # expõe a porta para o host
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: planner_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
    # ports:
    #   - "3333:3333"

volumes:
  pg_data:
