FROM node:20

# define a pasta de trabalho dentro do container
WORKDIR /app

# copia package.json e instala dependências
COPY package*.json ./
RUN npm install

# copia todo o código pro container
COPY . .

# compila o TypeScript
RUN npm run build

# inicia o servidor
CMD ["node", "dist/index.js"]
