
# # 1. Fase de Build
# FROM node:20-slim AS build

# WORKDIR /usr/src/app

# # Copia package.json e package-lock.json
# COPY package*.json ./

# # Instala todas as dependências (prod + dev)
# RUN npm install

# # Copia o código e o prisma
# COPY . .
# COPY prisma ./prisma

# # Gera Prisma Client
# RUN npx prisma generate

# # Compila TypeScript para JS
# RUN npm run build

# # 2. Fase de Produção
# FROM node:20-slim AS production

# WORKDIR /usr/src/app

# ENV NODE_ENV=production
# ENV DATABASE_URL=postgresql://planner:plannerpw@db:5432/plannerdb

# # Copia node_modules e dist da build
# COPY --from=build /usr/src/app/node_modules ./node_modules
# COPY --from=build /usr/src/app/dist ./dist
# COPY --from=build /usr/src/app/prisma ./prisma

# # Expõe a porta do Fastify
# EXPOSE 3333

# # Roda o JS compilado
# CMD ["node", "dist/server.js"]
