# 1. Imagem base
FROM node:20

# 2. Diretório de trabalho
WORKDIR /src

# 3. Copia package.json e package-lock.json
COPY package*.json ./

# 4. Instala dependências do projeto
RUN npm install

# 5. Instala TypeScript globalmente para poder usar 'tsc'
RUN npm install -g typescript

# 6. Copia o restante do projeto
COPY . .

# 7. Roda o build do TypeScript
RUN tsc

# 8. Expõe a porta que o backend usa
EXPOSE 4000

# 9. Comando para rodar o app
CMD ["node", "dist/index.js"]
